<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <Protobuf Include="..\..\..\protos\users\*.proto" GrpcServices="Client" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Grpc.AspNetCore"/>
        <PackageReference Include="Grpc.AspNetCore.Server.Reflection"/>
        <PackageReference Include="Grpc.Net.Client" />
        <PackageReference Include="Grpc.Tools" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Application\BlogCommentService.Application.Abstractions\BlogCommentService.Application.Abstractions.csproj" />
    </ItemGroup>

</Project>
